# Generated by Django 5.2.7 on 2025-10-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Caixa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Caixa (PDV)',
                'verbose_name_plural': 'Caixas (PDVs)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUPRIMENTO', 'Suprimento (Entrada)'), ('SANGRIA', 'Sangria (Saída)'), ('VENDA', 'Venda (Entrada Automática)')], max_length=20, verbose_name='Tipo de Movimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Movimento')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['data_movimento'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fechamento')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Inicial (Sangria)')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final (Fechamento)')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Fechamento')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
