# Generated by Django 5.2.7 on 2025-10-30 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='vendas.metodopagamento', verbose_name='Pagamento de Venda'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='vendas.venda', verbose_name='Venda Relacionada'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='caixa.caixa', verbose_name='Caixa'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='usuario_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_abertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Abertura'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='usuario_fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_fechadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Fechamento'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_avulsos', to='caixa.sessaocaixa', verbose_name='Sessão de Caixa'),
        ),
    ]
