# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percentual', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(default='LIVRE', max_length=10)),
                ('capacidade', models.IntegerField(default=4)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ABERTA', max_length=10)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('impresso_comanda', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('data_inclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ImpressaoComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_impressos', models.TextField()),
                ('local', models.CharField(max_length=20)),
                ('data_impressao', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.comanda')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valor_total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Bruto')),
                ('descontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descontos Aplicados')),
                ('valor_total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Líquido')),
                ('valor_servico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taxa de Serviço')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal (Bruto)')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto Aplicado')),
                ('total_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Venda')),
                ('movimento_estoque_criado', models.BooleanField(default=False, verbose_name='Mov. Estoque Gerado')),
                ('custo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo Total (CMV)')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('data_faturamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Faturamento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Cancelamento')),
                ('status', models.CharField(choices=[('ABERTA', 'Em Aberto / Rascunho'), ('FATURADA', 'Faturada (Estoque Baixado)'), ('CANCELADA', 'Cancelada (Estornada)')], db_index=True, default='ABERTA', max_length=20, verbose_name='Status')),
                ('tipo_pedido', models.CharField(choices=[('MESA', 'Mesa/Comanda'), ('DELIVERY', 'Delivery'), ('BALCAO', 'Balcão/Takeaway')], default='MESA', max_length=10, verbose_name='Tipo de Pedido')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atendente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.cliente', verbose_name='Cliente')),
                ('comanda_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.comanda', verbose_name='Comanda (origem)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'historical Venda',
                'verbose_name_plural': 'historical Vendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Bruto')),
                ('descontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descontos Aplicados')),
                ('valor_total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Líquido')),
                ('valor_servico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taxa de Serviço')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal (Bruto)')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto Aplicado')),
                ('total_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Venda')),
                ('movimento_estoque_criado', models.BooleanField(default=False, verbose_name='Mov. Estoque Gerado')),
                ('custo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo Total (CMV)')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('data_faturamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Faturamento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Cancelamento')),
                ('status', models.CharField(choices=[('ABERTA', 'Em Aberto / Rascunho'), ('FATURADA', 'Faturada (Estoque Baixado)'), ('CANCELADA', 'Cancelada (Estornada)')], db_index=True, default='ABERTA', max_length=20, verbose_name='Status')),
                ('tipo_pedido', models.CharField(choices=[('MESA', 'Mesa/Comanda'), ('DELIVERY', 'Delivery'), ('BALCAO', 'Balcão/Takeaway')], default='MESA', max_length=10, verbose_name='Tipo de Pedido')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente')),
                ('comanda_origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venda_associada', to='vendas.comanda', verbose_name='Comanda (origem)')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(default='DINHEIRO', max_length=20)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('custo_unitario_apurado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Unitário Apurado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='vendas.venda', verbose_name='Venda')),
            ],
        ),
    ]
