# Generated by Django 5.2.7 on 2025-11-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandaitem',
            name='nome_cliente_mesa',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome na Mesa'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='nome_cliente_mesa',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome na Mesa'),
        ),
    ]
