# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimento_base', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Rendimento Base (unidade de medida do produto produzido)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('custo_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Total da Receita')),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Unitário do Produto (R$/UN)')),
                ('produto_produzido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='estoque.produto', verbose_name='Produto Produzido')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'ordering': ('produto_produzido__nome',),
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_a_produzir', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade a Produzir')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('REQUISITANDO', 'Insumos Requisitados'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=15, verbose_name='Status da Ordem')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.fichatecnica', verbose_name='Produto a ser Produzido (Ficha Técnica)')),
                ('movimento_entrada_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_producao_entrada', to='estoque.movimentoestoque', verbose_name='Movimento de Entrada no Estoque (Produto Acabado)')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Emissão')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ('-data_emissao',),
            },
        ),
        migrations.CreateModel(
            name='RequisicaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDA', 'Atendida (Baixado do Estoque)'), ('PARCIAL', 'Atendida Parcialmente'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15, verbose_name='Status da Requisição')),
                ('data_requisicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Requisição')),
                ('movimento_saida_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicao_insumo_saida', to='estoque.movimentoestoque', verbose_name='Movimento de Saída no Estoque (Insumos)')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='producao.ordemproducao', verbose_name='Ordem de Produção Relacionada')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Requisição')),
            ],
            options={
                'verbose_name': 'Requisição de Insumo',
                'verbose_name_plural': 'Requisições de Insumos',
                'ordering': ('-data_requisicao',),
            },
        ),
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etapa', models.IntegerField(verbose_name='Etapa Nº')),
                ('tarefa', models.CharField(max_length=255, verbose_name='Tarefa / Passo Chave')),
                ('tempo_estimado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempo Estimado')),
                ('observacoes_qualidade', models.TextField(blank=True, null=True, verbose_name='Observações de Qualidade')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='producao.fichatecnica', verbose_name='Ficha Técnica')),
            ],
            options={
                'verbose_name': 'Etapa do Processo',
                'verbose_name_plural': 'Processo de Produção (Passos Chave)',
                'ordering': ['numero_etapa'],
                'unique_together': {('ficha_tecnica', 'numero_etapa')},
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Necessária')),
                ('custo_insumo', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo do Insumo')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.fichatecnica', verbose_name='Ficha Técnica')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_fichas', to='estoque.produto', verbose_name='Insumo (Produto de Estoque)')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'unique_together': {('ficha_tecnica', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Solicitada')),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Quantidade Atendida')),
                ('preco_custo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo Unitário (Momento da Baixa)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Insumo (Produto de Estoque)')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_requisicao', to='producao.requisicaoinsumo', verbose_name='Requisição de Insumo')),
            ],
            options={
                'verbose_name': 'Item da Requisição',
                'verbose_name_plural': 'Itens da Requisição',
                'unique_together': {('requisicao', 'insumo')},
            },
        ),
    ]
