# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_movimentada', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade Movimentada')),
                ('preco_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Preço/Custo usado para valorização do estoque no momento do movimento.', max_digits=10, verbose_name='Preço/Custo Unitário')),
            ],
            options={
                'verbose_name': 'Item de Movimento de Estoque',
                'verbose_name_plural': 'Itens de Movimento de Estoque',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('is_vendavel', models.BooleanField(default=False, help_text='Marcar se este produto pode ser vendido diretamente no PDV (Item de Cardápio).', verbose_name='Pode ser Vendido (Exibido no Cardápio)')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Saldo calculado do estoque. Não editável diretamente.', max_digits=15, verbose_name='Saldo Atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantidade mínima para disparar Ordem de Produção/Compra.', max_digits=15, verbose_name='Estoque Mínimo')),
                ('custo_medio_ponderado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, help_text='Custo Médio Ponderado (CMP) calculado com 4 casas decimais.', max_digits=15, verbose_name='Custo Médio Ponderado')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo unitário (arredondamento do CMP para 2 casas). É o custo padrão de exibição.', max_digits=10, verbose_name='Preço de Custo Padrão')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Venda')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Sistema')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_PRODUCAO', 'Entrada de Produto Acabado'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste/Inventário'), ('SAIDA_VENDA', 'Saída por Venda'), ('SAIDA_PRODUCAO', 'Saída para Produção (Insumo)'), ('SAIDA_AJUSTE', 'Saída por Perda/Inventário')], max_length=50, verbose_name='Tipo de Movimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente', verbose_name='Cliente (Se Venda)')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor', verbose_name='Fornecedor (Se Compra)')),
                ('pedido_compra', models.ForeignKey(blank=True, help_text='Vínculo com o pedido de compra que gerou esta entrada (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
