# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='venda',
            field=models.ForeignKey(blank=True, help_text='Vínculo com o pedido de venda que gerou esta saída (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda', verbose_name='Venda de Origem'),
        ),
        migrations.AddField(
            model_name='itemmovimentoestoque',
            name='movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.movimentoestoque', verbose_name='Movimento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidademedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='itemmovimentoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='itemmovimentoestoque',
            unique_together={('movimento', 'produto')},
        ),
    ]
