# Generated by Django 5.2.7 on 2025-11-04 01:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria'),
        ('estoque', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='responsavel',
            field=models.ForeignKey(default=1, help_text='Usuário que disparou este movimento (via API, Admin ou Sistema).', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=3, help_text='Define a organização na Ficha Técnica e Relatórios de Estoque.', on_delete=django.db.models.deletion.PROTECT, to='core.categoria', verbose_name='Categoria do Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='is_pre_pronto',
            field=models.BooleanField(default=False, help_text='Marcar se este produto é feito internamente e usado como insumo em outros produtos finais.', verbose_name='É Pré-Pronto/Produto Intermediário?'),
        ),
        migrations.CreateModel(
            name='AuditoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_auditoria', models.DateTimeField(auto_now_add=True, verbose_name='Data da Auditoria')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10, verbose_name='Status da Auditoria')),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade Contada em Campo')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Saldo do produto no momento em que a auditoria foi iniciada.', max_digits=15, verbose_name='Quantidade no Sistema')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Auditor')),
                ('movimento_ajuste', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_inventario_origem', to='estoque.movimentoestoque', verbose_name='Movimento de Ajuste Gerado')),
                ('produto', models.ForeignKey(limit_choices_to={'is_pre_pronto': False}, on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto (Insumo) Contado')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_inventario_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Contagem')),
            ],
            options={
                'verbose_name': 'Auditoria de Inventário (Insumos)',
                'verbose_name_plural': 'Auditorias de Inventário (Insumos)',
                'ordering': ['-data_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPrePronto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_auditoria', models.DateTimeField(auto_now_add=True, verbose_name='Data da Auditoria')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10, verbose_name='Status da Auditoria')),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade Contada em Campo')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Saldo do produto no momento em que a auditoria foi iniciada.', max_digits=15, verbose_name='Quantidade no Sistema')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Auditor')),
                ('movimento_ajuste', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_pre_pronto_origem', to='estoque.movimentoestoque', verbose_name='Movimento de Ajuste Gerado')),
                ('produto', models.ForeignKey(limit_choices_to={'is_pre_pronto': True}, on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto (Pré-Pronto) Contado')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_pre_pronto_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Contagem')),
            ],
            options={
                'verbose_name': 'Auditoria de Estoque (Pré-Prontos)',
                'verbose_name_plural': 'Auditorias de Estoque (Pré-Prontos)',
                'ordering': ['-data_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='ContagemDiariaFLV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contagem', models.DateTimeField(auto_now_add=True, verbose_name='Data da Contagem')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10, verbose_name='Status da Contagem')),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade Contada em Campo')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Saldo do produto no momento em que a contagem foi iniciada.', max_digits=15, verbose_name='Quantidade no Sistema')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Contagem')),
                ('movimento_ajuste', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagem_flv_origem', to='estoque.movimentoestoque', verbose_name='Movimento de Ajuste Gerado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto Contado (FLV)')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contagens_flv_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Contagem')),
            ],
            options={
                'verbose_name': 'Contagem Diária (FLV)',
                'verbose_name_plural': 'Contagens Diárias (FLV)',
                'ordering': ['-data_contagem'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Requisição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10, verbose_name='Status da Requisição')),
                ('quantidade_requisitada', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade Requisitada')),
                ('quantidade_entregue', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantidade efetivamente liberada e registrada como SAÍDA no estoque.', max_digits=15, verbose_name='Quantidade Entregue')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Solicitante')),
                ('movimento_saida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicao_origem', to='estoque.movimentoestoque', verbose_name='Movimento de Saída Gerado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto Requisitado')),
                ('responsavel_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Atendimento (Estoque)')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Produção/Cozinha)')),
            ],
            options={
                'verbose_name': 'Requisição de Estoque',
                'verbose_name_plural': 'Requisições de Estoque',
                'ordering': ['data_requisicao'],
            },
        ),
    ]
