# Generated by Django 5.2.7 on 2025-11-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentoestoque_responsavel_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmovimentoestoque',
            name='is_estornado',
            field=models.BooleanField(default=False, help_text="Se 'True', o item foi logicamente estornado e deve ser ignorado no cálculo do CMP e do Saldo.", verbose_name='Estornado'),
        ),
    ]
