# Generated by Django 5.2.7 on 2025-11-04 19:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_itemmovimentoestoque_is_estornado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='custo_medio_ponderado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_atual',
        ),
        migrations.CreateModel(
            name='CustoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Saldo calculado de estoque.', max_digits=15, verbose_name='Saldo Atual')),
                ('custo_medio_ponderado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Custo Médio Ponderado (CMP) calculado com 4 casas decimais.', max_digits=15, verbose_name='Custo Médio Ponderado')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo unitário (arredondamento do CMP para 2 casas).', max_digits=10, verbose_name='Preço de Custo Padrão')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização de Custo')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custo_produto', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Custo e Saldo do Produto',
                'verbose_name_plural': 'Custos e Saldos dos Produtos',
            },
        ),
    ]
