# Generated by Django 5.2.7 on 2025-11-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_produto_custo_medio_ponderado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstocagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Local')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Observações')),
                ('ativa', models.BooleanField(default=True, verbose_name='Local Ativo')),
            ],
            options={
                'verbose_name': 'Local de Estocagem',
                'verbose_name_plural': 'Locais de Estocagem',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='local_estocagem',
            field=models.ForeignKey(default=1, help_text='Onde este produto deve ser armazenado fisicamente.', on_delete=django.db.models.deletion.PROTECT, to='estoque.localestocagem', verbose_name='Local de Estocagem Padrão'),
            preserve_default=False,
        ),
    ]
