# Generated by Django 5.2.7 on 2025-11-09 14:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_itempedidocompra_options_and_more'),
        ('core', '0002_categoria'),
        ('estoque', '0006_localestocagem_produto_local_estocagem'),
        ('producao', '0001_initial'),
        ('vendas', '0002_comandaitem_nome_cliente_mesa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequisicaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Solicitada')),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Quantidade Atendida')),
            ],
            options={
                'verbose_name': 'Item de Requisição de Estoque',
                'verbose_name_plural': 'Itens de Requisição de Estoque',
            },
        ),
        migrations.AlterModelOptions(
            name='auditoriainventario',
            options={'verbose_name': 'Auditoria de Inventário', 'verbose_name_plural': 'Auditorias de Inventário'},
        ),
        migrations.AlterModelOptions(
            name='auditoriaprepronto',
            options={'verbose_name': 'Auditoria de Pré-Pronto', 'verbose_name_plural': 'Auditorias de Pré-Pronto'},
        ),
        migrations.AlterModelOptions(
            name='contagemdiariaflv',
            options={'verbose_name': 'Contagem Diária FLV', 'verbose_name_plural': 'Contagens Diárias FLV'},
        ),
        migrations.AlterModelOptions(
            name='localestocagem',
            options={'verbose_name': 'Local de Estocagem', 'verbose_name_plural': 'Locais de Estocagem'},
        ),
        migrations.AlterModelOptions(
            name='movimentoestoque',
            options={'verbose_name': 'Movimento de Estoque', 'verbose_name_plural': 'Movimentos de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='requisicaoestoque',
            options={'verbose_name': 'Requisição de Estoque', 'verbose_name_plural': 'Requisições de Estoque'},
        ),
        migrations.AlterUniqueTogether(
            name='itemmovimentoestoque',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='auditoriainventario',
            unique_together={('produto', 'data_auditoria')},
        ),
        migrations.AlterUniqueTogether(
            name='auditoriaprepronto',
            unique_together={('produto', 'data_auditoria')},
        ),
        migrations.AlterUniqueTogether(
            name='contagemdiariaflv',
            unique_together={('produto', 'data_contagem')},
        ),
        migrations.RemoveField(
            model_name='custoproduto',
            name='data_ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='custoproduto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='localestocagem',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_ultima_edicao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='movimento_saida',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='quantidade_entregue',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='quantidade_requisitada',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='responsavel_atendimento',
        ),
        migrations.RemoveField(
            model_name='requisicaoestoque',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='custoproduto',
            name='valor_total_estoque',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Valor Total em Estoque (Saldo * CMP)'),
        ),
        migrations.AddField(
            model_name='itemmovimentoestoque',
            name='item_origem_estorno',
            field=models.ForeignKey(blank=True, help_text='Se este item é uma reversão (ex: ENTRADA por cancelamento), aponta para o ItemMovimentoEstoque original que foi estornado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_estorno_reverso', to='estoque.itemmovimentoestoque', verbose_name='Item Original (em caso de estorno)'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.comanda', verbose_name='Comanda (Venda) de Origem'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='ordem_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.ordemproducao', verbose_name='Ordem de Produção de Origem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_insumo',
            field=models.BooleanField(default=False, verbose_name='É Insumo? (Matéria-prima/Componente)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo de Última Compra/Entrada'),
        ),
        migrations.AddField(
            model_name='requisicaoestoque',
            name='movimento_saida_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_estoque', to='estoque.movimentoestoque', verbose_name='Movimento de Saída de Estoque'),
        ),
        migrations.AddField(
            model_name='requisicaoestoque',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='data_auditoria',
            field=models.DateField(verbose_name='Data da Auditoria'),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='movimento_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_inventario', to='estoque.movimentoestoque', verbose_name='Movimento de Ajuste Gerado'),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='quantidade_contada',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Contada'),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='quantidade_sistema',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantidade do Sistema'),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Contagem'),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='data_auditoria',
            field=models.DateField(verbose_name='Data da Auditoria'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='movimento_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_pre_pronto', to='estoque.movimentoestoque', verbose_name='Movimento de Ajuste Gerado'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='produto',
            field=models.ForeignKey(limit_choices_to={'is_pre_pronto': True}, on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto Pré-Pronto'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='quantidade_contada',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Contada'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='quantidade_sistema',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantidade do Sistema'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Contagem'),
        ),
        migrations.AlterField(
            model_name='auditoriaprepronto',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='data_contagem',
            field=models.DateField(verbose_name='Data da Contagem'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='movimento_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_flv', to='estoque.movimentoestoque', verbose_name='Movimento de Ajuste Gerado'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto FLV'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='quantidade_contada',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Contada'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='quantidade_sistema',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantidade do Sistema'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Contagem'),
        ),
        migrations.AlterField(
            model_name='contagemdiariaflv',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='custoproduto',
            name='custo_medio_ponderado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Médio Ponderado (CMP)'),
        ),
        migrations.AlterField(
            model_name='custoproduto',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custo_info', to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='custoproduto',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='itemmovimentoestoque',
            name='is_estornado',
            field=models.BooleanField(default=False, help_text="Se 'True', o item foi logicamente estornado e deve ser ignorado no cálculo do CMP e do Saldo. O item reverso deve ser criado com item_origem_estorno preenchido.", verbose_name='Item Estornado'),
        ),
        migrations.AlterField(
            model_name='localestocagem',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='localestocagem',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='data_movimento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Estoque Mínimo (Alerta)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_pre_pronto',
            field=models.BooleanField(default=False, verbose_name='É Pré-Pronto/Semi-acabado?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_vendavel',
            field=models.BooleanField(default=True, verbose_name='É Vendável? (Produto Final)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='local_estocagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localestocagem', verbose_name='Local de Estocagem Padrão'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='requisicaoestoque',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=50, verbose_name='Status da Requisição'),
        ),
        migrations.AddConstraint(
            model_name='itemmovimentoestoque',
            constraint=models.UniqueConstraint(fields=('item_origem_estorno',), name='unique_estorno_reverso'),
        ),
        migrations.AddField(
            model_name='itemrequisicaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto Solicitado'),
        ),
        migrations.AddField(
            model_name='itemrequisicaoestoque',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_requisicao', to='estoque.requisicaoestoque', verbose_name='Requisição de Estoque'),
        ),
        migrations.RemoveField(
            model_name='auditoriainventario',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='auditoriainventario',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='auditoriaprepronto',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='auditoriaprepronto',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='contagemdiariaflv',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='contagemdiariaflv',
            name='observacoes',
        ),
    ]
