# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição (Opcional)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa no Cardápio')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Cardápio',
                'verbose_name_plural': 'Categorias de Cardápio',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, verbose_name='Descrição para Cardápio')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='menu.categoriacardapio', verbose_name='Categoria do Cardápio')),
                ('produto', models.OneToOneField(limit_choices_to={'is_vendavel': True}, on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto de Estoque')),
            ],
            options={
                'verbose_name': 'Item de Cardápio',
                'verbose_name_plural': 'Itens de Cardápio',
            },
        ),
    ]
