# Generated by Django 5.2.7 on 2025-10-30 23:35

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContasAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('A_PAGAR', 'A Pagar'), ('PAGO', 'Pago/Liquidado'), ('CANCELADO', 'Cancelado')], default='A_PAGAR', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contabilizado_pagamento', models.BooleanField(default=False, verbose_name='Pagamento Contabilizado?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Pedida')),
                ('preco_unitario_negociado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário Negociado')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantidade Recebida')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens dos Pedidos de Compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(default=datetime.date.today, verbose_name='Data do Pedido')),
                ('data_prevista_recebimento', models.DateField(blank=True, null=True, verbose_name='Previsão de Recebimento')),
                ('total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Líquido')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Envio'), ('ENVIADO', 'Enviado ao Fornecedor'), ('RECEBIDO', 'Recebido e Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, verbose_name='Status')),
                ('movimento_criado', models.BooleanField(default=False, verbose_name='Movimento de Estoque Criado?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-data_pedido', '-data_criacao'],
            },
        ),
    ]
