# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='core.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_pagar_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
    ]
