# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidocompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='pedido_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra', verbose_name='Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_pagar', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedidocompra',
            unique_together={('pedido_compra', 'produto')},
        ),
    ]
