# Generated by Django 5.2.7 on 2025-11-04 01:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
        ('core', '0002_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocompra',
            name='usuario_criacao',
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Criação'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar_fornecedor', to='core.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='pedido_compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='status',
            field=models.CharField(choices=[('A_PAGAR', 'A Pagar'), ('PAGO_PARCIAL', 'Pago Parcialmente'), ('PAGO_TOTAL', 'Pago Totalmente/Liquidado'), ('CANCELADO', 'Cancelado')], default='A_PAGAR', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Original'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='preco_unitario_negociado',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Preço Unitário Negociado'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade_pedida',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade Pedida'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Quantidade Recebida'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (Rascunho)'), ('AGUARDANDO', 'Aguardando Envio'), ('ENVIADO', 'Enviado ao Fornecedor'), ('RECEBIDO_PARCIAL', 'Recebido Parcialmente'), ('FINALIZADO', 'Recebido e Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='total_liquido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Total Líquido'),
        ),
    ]
