# Generated by Django 5.2.7 on 2025-11-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_pedidocompra_usuario_criacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContasAPagar',
        ),
    ]
