# Generated by Django 5.2.7 on 2025-11-09 14:00

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_delete_contasapagar'),
        ('core', '0002_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedidocompra',
            options={'verbose_name': 'Item do Pedido de Compra', 'verbose_name_plural': 'Itens dos Pedidos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'ordering': ['-data_emissao', 'pk'], 'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='data_prevista_recebimento',
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='total_liquido',
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_emissao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega Prevista'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='valor_total',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Calculado automaticamente pela soma dos itens. 4 casas decimais para precisão.', max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='movimento_criado',
            field=models.BooleanField(default=False, verbose_name='Movimento Estoque/Contas a Pagar Criado'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='observacoes',
            field=models.TextField(blank=True, default='Coloque suas obervações aqui:', verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (Rascunho)'), ('AGUARDANDO', 'Aguardando Envio'), ('ENVIADO', 'Enviado ao Fornecedor'), ('RECEBIDO_PARCIAL', 'Recebido Parcialmente'), ('FINALIZADO', 'Recebido e Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=50, verbose_name='Status'),
        ),
    ]
