# Generated by Django 5.2.7 on 2025-11-04 17:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0005_delete_contasapagar'),
        ('core', '0002_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('A_PAGAR', 'A Pagar'), ('PAGO_PARCIAL', 'Pago Parcialmente'), ('PAGO_TOTAL', 'Pago Totalmente/Liquidado'), ('CANCELADO', 'Cancelado')], default='A_PAGAR', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contabilizado_pagamento', models.BooleanField(default=False, verbose_name='Pagamento Contabilizado?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar_fornecedor', to='core.fornecedor', verbose_name='Fornecedor')),
                ('pedido_compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_pagar_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
