# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('compras', '0002_initial'),
        ('contabil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcentrocusto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='centro_custo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='movimento_caixa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.movimentocaixa', verbose_name='Movimento de Caixa de Origem'),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem'),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
    ]
