# Generated by Django 5.2.7 on 2025-10-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0002_initial'),
        ('compras', '0003_initial'),
        ('contabil', '0002_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='venda',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.venda', verbose_name='Venda de Origem'),
        ),
        migrations.AddField(
            model_name='historicalplanoconta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplanoconta',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contabil.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='movimento_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_contabeis', to='caixa.movimentocaixa', verbose_name='Movimento de Caixa de Origem'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_contabeis', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_contabeis_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_contabeis', to='vendas.venda', verbose_name='Venda de Origem'),
        ),
        migrations.AddField(
            model_name='planoconta',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_filhas', to='contabil.planoconta', verbose_name='Conta Pai'),
        ),
        migrations.AddField(
            model_name='planoconta',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano_contas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='plano_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contabil.planoconta', verbose_name='Conta Contábil'),
        ),
        migrations.AddField(
            model_name='historicalplanoconta',
            name='conta_pai',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.planoconta', verbose_name='Conta Pai'),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='plano_conta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.planoconta', verbose_name='Conta Contábil'),
        ),
    ]
