# Generated by Django 5.2.7 on 2025-11-04 18:57

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_initial'),
        ('compras', '0005_delete_contasapagar'),
        ('contabil', '0003_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallancamentocontabil',
            name='movimento_caixa',
        ),
        migrations.RemoveField(
            model_name='historicallancamentocontabil',
            name='pedido_compra',
        ),
        migrations.RemoveField(
            model_name='historicallancamentocontabil',
            name='usuario_criacao',
        ),
        migrations.RemoveField(
            model_name='historicallancamentocontabil',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='movimento_caixa',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='pedido_compra',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='usuario_criacao',
        ),
        migrations.RemoveField(
            model_name='lancamentocontabil',
            name='venda',
        ),
        migrations.CreateModel(
            name='HistoricalLoteContabil',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Registro')),
                ('historico_transacao', models.CharField(max_length=255, verbose_name='Histórico da Transação')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Lote')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimento_caixa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caixa.movimentocaixa', verbose_name='Movimento de Caixa de Origem')),
                ('pedido_compra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem')),
                ('usuario_criacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('venda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.venda', verbose_name='Venda de Origem')),
            ],
            options={
                'verbose_name': 'historical Lote Contábil (Transação)',
                'verbose_name_plural': 'historical Lotes Contábeis (Transações)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoteContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Registro')),
                ('historico_transacao', models.CharField(max_length=255, verbose_name='Histórico da Transação')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Lote')),
                ('movimento_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_contabeis', to='caixa.movimentocaixa', verbose_name='Movimento de Caixa de Origem')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_contabeis', to='compras.pedidocompra', verbose_name='Pedido de Compra de Origem')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_contabeis_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_contabeis', to='vendas.venda', verbose_name='Venda de Origem')),
            ],
            options={
                'verbose_name': 'Lote Contábil (Transação)',
                'verbose_name_plural': 'Lotes Contábeis (Transações)',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='lote_contabil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.lotecontabil', verbose_name='Lote Contábil'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='lote_contabil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='contabil.lotecontabil', verbose_name='Lote Contábil'),
            preserve_default=False,
        ),
    ]
